### PR TITLE
fix: rework knock client usage

### LINKED ISSUE #19: The client does not user persistent connections to send HTTP requests
The code that creates a Net::HTTP connection uses `.new` to initialize a connection object here
https://github.com/knocklabs/knock-ruby/blob/main/lib/knock/client.rb#L40-L47

The client will create a new connection for every request which is not efficient, will be slower and probably use up more resources(file descriptors) on the server if there is high traffic.

Also from the[ docs here 
](url)
>If you wish to re-use a connection across multiple [HTTP](https://ruby-doc.org/stdlib-3.0.2/libdoc/net/http/rdoc/Net/HTTP.html) requests without automatically closing it you can use [::new](https://ruby-doc.org/stdlib-3.0.2/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new) and then call [start](https://ruby-doc.org/stdlib-3.0.2/libdoc/net/http/rdoc/Net/HTTP.html#method-i-start) and [finish](https://ruby-doc.org/stdlib-3.0.2/libdoc/net/http/rdoc/Net/HTTP.html#method-i-finish) manually.

It might be possible to change the existing code to use `start` and `finish` for reusing connections. Alternately you could switch to using Faraday or another client that supports persistent connections out of the box

### PR DESCRIPTION
**Pull request by cjbell**
* removes net:http as a singleton as it is not thread safe
* introduces a new `Knock.config` block to configure read/write timeouts in net:http
* introduces a new timeout error when a timeout occurs

Closes #19

### CODE REVIEW

**Review by bceskavich — APPROVED** [review]

File: lib/knock/client.rb [hunk 1]
```diff
@@ -6,16 +6,22 @@ module Client
...
-      @client = Net::HTTP.new(Knock::API_HOSTNAME, 443)
-      @client.use_ssl = true
-
-      @client
+      Net::HTTP.new(Knock.config.api_hostname, 443).tap do |http_client|
+        http_client.use_ssl = true
+        http_client.open_timeout = Knock.config.timeout
+        http_client.read_timeout = Knock.config.timeout
+        http_client.write_timeout = Knock.config.timeout if RUBY_VERSION >= '2.6.0'
+      end
```
Comment (manumahajan) [inline lib/knock/client.rb:14]: This will create a new client for every request. While it will work it is not ideal for performance. 

As an alternate you could use a connection pool via [connection pool gem](https://github.com/mperham/connection_pool) and that way you can reuse the connections. Something like the following: 

```
@pool = ConnectionPool.new(size: 5) { client }


pool.with |client| do
  client.request(request)
end
```

If you do decide to create a pool then it would be good to also have a configuration to use [sessions](https://docs.ruby-lang.org/en/3.2/Net/HTTP.html#class-Net::HTTP-label-HTTP+Sessions) and then you can include a call to `start` when you create a client. 

```
http_client.start if Knock.config.use_sessions
```

File: lib/knock/client.rb [hunk 2]
```diff
@@ -6,16 +6,22 @@ module Client
...
     end
 
     def execute_request(request:)
-      response = client.request(request)
+      begin
+        response = client.request(request)
+      rescue Net::OpenTimeout, Net::ReadTimeout, Net::WriteTimeout
+        raise TimeoutError.new(
+          message: 'API Timeout Error',
```
Comment (manumahajan) [inline lib/knock/client.rb:22]: Nit: would be good to include the original error here to know what kind of timeout it is.

**Review by manumahajan — COMMENTED** [review]
This is great! Thanks for the quick turnaround on this.

This solves the issue of client not being threadsafe so it's a big improvement!

I have a couple of suggestion about using a connection pool and exposing a configuration to start a session which would improve performance dramatically.

**Review by natperpepaj — APPROVED** [review]
